plugins {
    id 'com.android.application' version '8.13.2' apply false
    id 'com.android.library' version '8.13.2' apply false
    id 'com.vanniktech.maven.publish' version '0.36.0' apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

ext {
    // Sdk and tools
    minSdkVersion = 21
    targetSdkVersion = 36
    compileSdkVersion = 36

    // App dependencies
    appCompatVersion = '1.7.1'
    materialVersion = '1.13.0'
    constraintlayoutVersion = '2.2.1'
    lottieVersion = '6.7.1'
    adsVersion = '23.6.0'
}
